### ISSUE TITLE
添加自定义日志实现支持

### ISSUE THREAD

**Issue by xiao-cao-x** [tencent-connect/botgo#11]
log直接打印在终端里很不合理(os.Exit也不应该出现 应该返回err让使用者自己处理)
应该支持使用者自定义日志的实现

**Comment by vissong** [comment]
e697512 提供了一个如何自定义 logger 的例子。另外原来 os.Exit 的两处，是由于发生对应错误之后，无法再进行 resume 和 identify，不过直接退出不太合适，已经修改为 panic，由开发者自行处理。

**Comment by xiao-cao-x** [comment]
好的呢 谢谢啦
