### ISSUE TITLE
parseAndHandle failed, The operation completed successfully.

### ISSUE THREAD

**Issue by xiao-cao-x** [tencent-connect/botgo#13]
```console
16:12:55 [Error]:[ws][ID:a2ef19e8-535d-4a99-aae6-1a1f5776b4f0][Shard:(0/1)][Intent:1073741824] parseAndHandle failed, The operation completed successfully.文件:client.go,行:132
```
![image](https://user-images.githubusercontent.com/76673990/147544945-821ecda6-8f3a-4546-bb9f-a8df08b4e5d1.png)
![image](https://user-images.githubusercontent.com/76673990/147544956-046b08e9-be81-4dbe-8db5-80424b0a854b.png)
![image](https://user-images.githubusercontent.com/76673990/147547113-5049b712-96e2-4441-8085-06f9f6ab1569.png)

因为什么?

**Comment by xiao-cao-x** [comment]
PostMessage 时会这样 功能不受影响

**Comment by vissong** [comment]
这个是接收消息的时候 handler 返回了错误，看下你的 handler 在完成了逻辑之后是否 rerun 了一个 err，如果没有报错，应该返回  `nil`

**Comment by xiao-cao-x** [comment]
> 这个是接收消息的时候 handler 返回了错误，看下你的 handler 在完成了逻辑之后是否 rerun 了一个 err，如果没有报错，应该返回 `nil`

好吧 我的问题, syscall.Syscall 总是返回一个err而不是`nil` 里面的信息是 success
