### ISSUE TITLE
issue(optimize): recover goroutine panic & output call stack

### ISSUE THREAD

**Issue by 1046102779** [tencent-connect/botgo#15]
<img width="1376" alt="wecom-temp-1ddf07eddc910f96ed763d87f86664fa" src="https://user-images.githubusercontent.com/20457624/148214248-73e4c49e-1f8d-48db-8444-8bd507ca9206.png">

![wecom-temp-fa0028500c783cf5eb97a181cc1e1095](https://user-images.githubusercontent.com/20457624/148214581-fd325d27-2e80-4a8d-a046-f566d02ffa97.png)

**Comment by vissong** [comment]
fixed in 9c2a97c
