### ISSUE TITLE
登录成功以及被强制登出回调

### ISSUE THREAD

**Issue by xiao-cao-x** [tencent-connect/botgo#16]
现在的SDK有这个功能吗?
如果没有的话 需要新增

**Comment by xiao-cao-x** [comment]
因为Start后如果成功就是阻塞线程 没有任何提示 这让用户交互很难做

**Comment by vissong** [comment]
这里没有登入登出操作，可以结合具体的指令时候描述下需求

**Comment by xiao-cao-x** [comment]
> 这里没有登入登出操作，可以结合具体的指令时候描述下需求

就比如 那个op码 发来个 hello(好像是9)来 就通知下 登录成功

**Comment by vissong** [comment]
已经在 9242dae 提供，使用方法参考  `example/receive-and-send`

**Comment by xiao-cao-x** [comment]
> 已经在 9242dae 提供，使用方法参考  `examples/receive-and-send` 

哇哦 你是在美国吗这个时间点提交
