### ISSUE TITLE
接口: 机器人频道列表返回人数

### ISSUE THREAD

**Issue by RealHeart** [tencent-connect/botgo#18]
## 想要的能力是

/users/@me/guilds 返回频道人数

## 基于想要的能力，能够实现的是

统计总频道人数

## 如果未提供该能力，造成的影响是

循环调用频道信息接口获取

**Comment by Antecer** [comment]
另外,建议`/users/@me/guilds`接口返回的`IsOwner: bool`字段,直接改成`Owner: User`字段.
也就是说直接返回创建者的`User`对象,因为`IsOwner`这个属性可以说是完全无用,
其一,机器人不能创建频道;其二,目标频道是否是自己的频道根本就不需要判断,这是请求发起者自己就能知道的已知属性.
改成`User`对象会更有用处,有利于机器人对服务的频道进行过滤和筛查,后期对于内容风控也更方便把握,可以拒绝对黑名单频道主进行服务.

**Comment by vissong** [comment]
> 另外,建议`/users/@me/guilds`接口返回的`IsOwner: bool`字段,直接改成`Owner: User`字段.
> 也就是说直接返回创建者的`User`对象,因为`IsOwner`这个属性可以说是完全无用,
> 其一,机器人不能创建频道;其二,目标频道是否是自己的频道根本就不需要判断,这是请求发起者自己就能知道的已知属性.
> 改成`User`对象会更有用处,有利于机器人对服务的频道进行过滤和筛查,后期对于内容风控也更方便把握,可以拒绝对黑名单频道主进行服务.

IsOwner 是为了未来能够放开普通用户 oauth 调用的时候用于识别是否是自己创建的频道所用。

返回 Owner 的 User 信息，对于此接口所需要获取的数据，会带来更多的内部请求，我们也和产品以其评估下这里的优先级。

**Comment by vissong** [comment]
线上接口已更新
