### ISSUE TITLE
[BUG] 机器人发送的消息会被服务器删除部分字符

### ISSUE THREAD

**Issue by Antecer** [tencent-connect/botgo#22]
![image](https://user-images.githubusercontent.com/8684916/149667478-46f13493-d0fa-4d9f-9884-fed148bd1c00.png)
![image](https://user-images.githubusercontent.com/8684916/149667428-4e01f518-0ed2-4960-abb7-ff9edbd297a4.png)

如图,经过多次测试,发现当字符串为 json数组,且item个数超过1个的时候,string成员的下划线会被服务器删除掉!

**Comment by Antecer** [comment]
好吧，经过和开发者社区的众多成员讨论后得知，原来这是后端把markdown格式全给删掉了，从而导致影响了正常消息。
奇怪的地方是，markdown它只是一种前端标记语言，咋还进行后端替换格式的？这样很浪费服务器资源吧。

如果确实要限制机器人发送markdown，建议给markdown添加识别前缀，如代码段转义符：
```
	```md
	这里写markdown内容，这样就不影响机器人发送的普通消息字符被替换了
	```
```

**Comment by vissong** [comment]
目前会过滤此内容充的 markdown 标记，比较早期的策略，我们确认下是否还需要过滤。

**Comment by Antecer** [comment]
markdown 的标记符号实在太多了，已经影响了正常文本的显示了。
所以，再次建议要搞markdown的话，给框到反引号区域。顺便还能支持下多种代码块的高亮格式。

**Comment by vissong** [comment]
发送消息时，content 内容已经不过滤 markdown 标记。
