### ISSUE TITLE
生产环境如何关闭默认日志？

### ISSUE THREAD

**Issue by Baiyuetribe** [tencent-connect/botgo#35]
![image](https://user-images.githubusercontent.com/43716063/216898492-69c03278-0e80-40f6-81ad-231f1dc43b18.png)
找了很久，没看到可关闭的选项，难到要手动到源码里去关闭这些输出吗？

**Comment by thesixonenine** [comment]
@Baiyuetribe 自定义Logger来关闭, 参考 #11
