### ISSUE TITLE
QQ开发平台的问题，注册期间中途退出导致邮箱无法再次注册

### ISSUE THREAD

**Issue by foxwhite25** [tencent-connect/botgo#4]
虽然说这个不是QQ开发平台的repo，但是这是能找到最近的地方了。腾讯客服一直都是Bot，没卵用，也没有对应开发平台的选项。如果知道有什么地方可以反馈，欢迎告诉我。

## 复现流程：

1. 前往 https://bot.q.qq.com/open/#/bot/register?type=1 注册个人账户
2. 到 绑定管理员 步骤退出
3. 再次使用相同邮箱注册
4. 将显示该邮箱已被占用，请更换邮箱
5. 这时候前往使用该邮箱登陆，会出现读数据库失败的错误

## 可能原因：

写这个网页的人大概是注册到一半就写入数据库了，登陆也没有错误处理，导致如果后面步骤没做完就会有数据库错误

**Comment by vissong** [comment]
这个问题在修复中了，另外这里是在注册个人开发者么？是否已经在我们的官方频道中？

**Comment by woshiliuxu** [comment]
加1，多久修复。

**Comment by foxwhite25** [comment]
> 这个问题在修复中了，另外这里是在注册个人开发者么？是否已经在我们的官方频道中？

没有在官方频道，是个人开发者申请，现在已经换了个邮箱注册成功了

**Comment by vissong** [comment]
如果没有在官方开发者频道中，请先加群，申请开发者之后会自动被添加到官方频道 652987290

**Comment by foxwhite25** [comment]
> 如果没有在官方开发者频道中，请先加群，申请开发者之后会自动被添加到官方频道 652987290

这个群号找不到

**Comment by vissong** [comment]
> 

这个群号貌似被设置了不允许搜索，不知道你注册成功了没有？如果注册成功了应该已经在官方频道中了

**Comment by woshiliuxu** [comment]
> > 
> 
> 这个群号貌似被设置了不允许搜索，不知道你注册成功了没有？如果注册成功了应该已经在官方频道中了

我注册成功了，但是并没有被拉入官方频道中。

**Comment by vissong** [comment]
@woshiliuxu 可以发我 qq 号，  @foxwhite25 如果还有问题也可以邮件给我下 qq 

vissong@tencent.com

**Comment by woshiliuxu** [comment]
> @woshiliuxu 可以发我 qq 号， @foxwhite25 如果还有问题也可以邮件给我下 qq
> 
> [vissong@tencent.com](mailto:vissong@tencent.com)

1057181419 这是我的QQ号

**Comment by foxwhite25** [comment]
> @woshiliuxu 可以发我 qq 号， @foxwhite25 如果还有问题也可以邮件给我下 qq
> 
> [vissong@tencent.com](mailto:vissong@tencent.com)

我已经被拉进去了
