### ISSUE TITLE
[NodeSDK] 纠错    |    处理完后本条issue自行删除

### ISSUE THREAD

**Issue by ryuujo1573** [tencent-connect/botgo#9]
[Typo Link](https://bot.q.qq.com/wiki/develop/nodesdk/#%E5%BD%93%E5%89%8D%E7%89%88%E6%9C%AC)
* typo: `creatOpenAPI` -> `createOpenApi`
* typo: `creatWebsocket` -> `createWebSocket`

**Comment by ryuujo1573** [comment]
没有在 npmjs 或者在 docs 页面找到反馈入口，如果看到这里的您方便地话可以代为处理一下的话非常感谢

**Comment by vissong** [comment]
已反馈相关同学处理

**Comment by ryuujo1573** [comment]
谢谢
